/**
 * API Service Layer
 * 
 * Placeholder functions for backend integration.
 * Replace these with actual API calls once your backend is ready.
 * 
 * Environment variables (from .env):
 * - VITE_API_BASE_URL: Your backend API base URL
 * - VITE_GITHUB_USERNAME: Your GitHub username
 * - VITE_GITHUB_TOKEN: GitHub personal access token (optional)
 * - VITE_EMAILJS_*: EmailJS credentials (if using EmailJS)
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '';
const GITHUB_USERNAME = import.meta.env.VITE_GITHUB_USERNAME || 'varunntech';
const GITHUB_TOKEN = import.meta.env.VITE_GITHUB_TOKEN || '';

// ==================== CONTACT FORM ====================

/**
 * Submit contact form data to backend
 * @param {Object} formData - { name, email, message }
 * @returns {Promise<Object>} - { success: boolean, message: string }
 */
export const submitContactForm = async (formData) => {
  // TODO: Replace with your actual backend endpoint
  // Example using fetch:
  // const response = await fetch(`${API_BASE_URL}/contact`, {
  //   method: 'POST',
  //   headers: { 'Content-Type': 'application/json' },
  //   body: JSON.stringify(formData)
  // });
  // return response.json();

  // Placeholder: Simulate API call
  console.log('Contact form submitted:', formData);

  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        message: 'Message sent successfully! I will get back to you soon.'
      });
    }, 1500);
  });
};

/**
 * Submit contact form using EmailJS
 * Requires EmailJS account and environment variables
 */
export const submitContactFormEmailJS = async (formData) => {
  // TODO: Implement EmailJS integration
  // import emailjs from '@emailjs/browser';
  // 
  // const serviceId = import.meta.env.VITE_EMAILJS_SERVICE_ID;
  // const templateId = import.meta.env.VITE_EMAILJS_TEMPLATE_ID;
  // const publicKey = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;
  //
  // return emailjs.send(serviceId, templateId, formData, publicKey);

  throw new Error('EmailJS not configured. Set up environment variables first.');
};

// ==================== GITHUB API ====================

/**
 * Fetch GitHub user stats
 * @returns {Promise<Object>} - GitHub user data
 */
export const fetchGitHubStats = async () => {
  try {
    const response = await fetch(`https://api.github.com/users/${GITHUB_USERNAME}`);
    if (response.ok) {
      return await response.json();
    }
  } catch (error) {
    console.error('Error fetching GitHub stats:', error);
  }

  // Placeholder data fallback if offline or rate-limited
  return {
    public_repos: 18,
    followers: 12,
    following: 10,
    public_gists: 0,
    bio: 'Data Analyst | MCA Data Science | ML & AI Enthusiast',
    location: 'India'
  };
};

/**
 * Fetch GitHub repositories
 * @param {number} perPage - Number of repos to fetch
 * @returns {Promise<Array>} - Array of repository objects
 */
export const fetchGitHubRepos = async (perPage = 6) => {
  // TODO: Replace with actual GitHub API call
  // const headers = GITHUB_TOKEN ? { Authorization: `token ${GITHUB_TOKEN}` } : {};
  // const response = await fetch(
  //   `https://api.github.com/users/${GITHUB_USERNAME}/repos?sort=updated&per_page=${perPage}`,
  //   { headers }
  // );
  // return response.json();

  // Placeholder data
  return [
    {
      id: 1,
      name: 'netflix-data-analysis',
      description: 'Comprehensive EDA of Netflix content catalog with Power BI dashboards',
      language: 'Python',
      stargazers_count: 12,
      forks_count: 3,
      updated_at: '2024-11-15T00:00:00Z',
      html_url: `https://github.com/${GITHUB_USERNAME}/netflix-data-analysis`
    },
    {
      id: 2,
      name: 'churn-prediction-ml',
      description: 'Customer churn prediction using ensemble ML models',
      language: 'Jupyter Notebook',
      stargazers_count: 8,
      forks_count: 2,
      updated_at: '2024-10-20T00:00:00Z',
      html_url: `https://github.com/${GITHUB_USERNAME}/churn-prediction-ml`
    },
    {
      id: 3,
      name: 'sales-dashboard-powerbi',
      description: 'Interactive retail sales dashboard with DAX measures',
      language: 'PowerShell',
      stargazers_count: 5,
      forks_count: 1,
      updated_at: '2024-09-10T00:00:00Z',
      html_url: `https://github.com/${GITHUB_USERNAME}/sales-dashboard-powerbi`
    },
  ];
};

/**
 * Get GitHub README stats image URLs
 * These are generated by github-readme-stats.vercel.app
 * Replace 'your-username' with your actual GitHub username
 */
export const getGitHubStatsUrls = () => {
  const username = GITHUB_USERNAME;
  const theme = 'radical';

  return {
    statsCard: `https://github-readme-stats.shion.dev/api?username=${username}&show_icons=true&theme=${theme}&hide_border=true&count_private=true`,
    topLanguages: `https://github-readme-stats.shion.dev/api/top-langs/?username=${username}&layout=compact&theme=${theme}&hide_border=true`,
    streakStats: `https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=${theme}&hide_border=true`,
    contributionGraph: `https://github-readme-activity-graph.vercel.app/graph?username=${username}&theme=github-compact&hide_border=true`
  };
};

// ==================== PROJECTS API (Future Backend) ====================

/**
 * Fetch projects from backend
 * @returns {Promise<Array>} - Array of project objects
 */
export const fetchProjects = async () => {
  // TODO: Replace with actual API call
  // const response = await fetch(`${API_BASE_URL}/projects`);
  // return response.json();

  // For now, import from local data
  const { projects } = await import('../data/projects.js');
  return projects;
};

/**
 * Fetch single project by ID
 * @param {number} id - Project ID
 */
export const fetchProjectById = async (id) => {
  // TODO: Replace with actual API call
  // const response = await fetch(`${API_BASE_URL}/projects/${id}`);
  // return response.json();

  const { projects } = await import('../data/projects.js');
  return projects.find(p => p.id === id);
};

// ==================== ANALYTICS (Optional) ====================

/**
 * Track page view or event (Google Analytics, Plausible, etc.)
 * @param {string} eventName - Event name
 * @param {Object} params - Event parameters
 */
export const trackEvent = (eventName, params = {}) => {
  // TODO: Integrate with your analytics provider
  // Example: gtag('event', eventName, params);

  if (import.meta.env.DEV) {
    console.log('Analytics event:', eventName, params);
  }
};

// ==================== REVIEWS / TESTIMONIALS API ====================

import { supabase } from './supabase';

/**
 * Fetch approved reviews from Supabase
 * @returns {Promise<Array>} - List of approved reviews
 */
export const fetchApprovedReviews = async () => {
  if (!supabase) {
    // Fallback Mock reviews if Supabase is not yet configured
    return [
      {
        id: 1,
        name: 'Aman Sharma',
        role: 'Data Analyst at TechCorp',
        message: 'Varun possesses a rare talent for translating complex analytical theories into practical visualizations. Highly recommended!',
        created_at: '2026-07-01T00:00:00Z'
      },
      {
        id: 2,
        name: 'Shivansh Chaurasiya',
        role: 'Freelance Client',
        message: 'The Veloura shopping platform developed by Varun is extremely fast and robust. The UI design flows smoothly and works flawlessly on all mobile devices.',
        created_at: '2026-06-15T00:00:00Z'
      }
    ];
  }

  try {
    const { data, error } = await supabase
      .from('reviews')
      .select('*')
      .eq('approved', true)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('Error fetching approved reviews:', error);
    return [];
  }
};

/**
 * Submit a new review to Supabase (pending approval)
 * @param {Object} reviewData - { name, email, role, message }
 * @returns {Promise<Object>} - { success: boolean, message: string }
 */
export const submitReview = async (reviewData) => {
  if (!supabase) {
    console.log('Supabase offline. Simulated review submit:', reviewData);
    return {
      success: true,
      message: 'Review simulated successfully! Wire up Supabase to persist reviews.'
    };
  }

  try {
    const { error } = await supabase
      .from('reviews')
      .insert([
        {
          name: reviewData.name,
          email: reviewData.email,
          role: reviewData.role || '',
          message: reviewData.message,
          approved: false // Default to false (requires manual approval)
        }
      ]);

    if (error) throw error;

    return {
      success: true,
      message: 'Review submitted successfully! It will appear on the website once approved by Varun.'
    };
  } catch (error) {
    console.error('Error submitting review:', error);
    return {
      success: false,
      message: 'Failed to submit review. Please try again later.'
    };
  }
};
